name: musterikategorizasyon
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_messaging: ^14.0.3
  google_maps_flutter: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.6.1
  geolocator: ^10.0.1
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
