// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMWz-y6mP0BCIFbwgWrShgDHR8ZeJsn8g',
    appId: '1:596270852402:web:9bdf79d321caccb0d04f2b',
    messagingSenderId: '596270852402',
    projectId: 'musterikategorizasyonu',
    authDomain: 'musterikategorizasyonu.firebaseapp.com',
    storageBucket: 'musterikategorizasyonu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdWrxd7ECN91rbLc0bLRufgWOC9x-SZ_c',
    appId: '1:596270852402:android:702020908507e680d04f2b',
    messagingSenderId: '596270852402',
    projectId: 'musterikategorizasyonu',
    storageBucket: 'musterikategorizasyonu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI7RfRHfllTurC_oJyTd8AG62wzKzRWlY',
    appId: '1:596270852402:ios:fb1003b5a145a78fd04f2b',
    messagingSenderId: '596270852402',
    projectId: 'musterikategorizasyonu',
    storageBucket: 'musterikategorizasyonu.appspot.com',
    iosBundleId: 'com.example.musterikategorizasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI7RfRHfllTurC_oJyTd8AG62wzKzRWlY',
    appId: '1:596270852402:ios:fb1003b5a145a78fd04f2b',
    messagingSenderId: '596270852402',
    projectId: 'musterikategorizasyonu',
    storageBucket: 'musterikategorizasyonu.appspot.com',
    iosBundleId: 'com.example.musterikategorizasyon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMWz-y6mP0BCIFbwgWrShgDHR8ZeJsn8g',
    appId: '1:596270852402:web:694f770c86d65bc3d04f2b',
    messagingSenderId: '596270852402',
    projectId: 'musterikategorizasyonu',
    authDomain: 'musterikategorizasyonu.firebaseapp.com',
    storageBucket: 'musterikategorizasyonu.appspot.com',
  );

}